export const FETCH_TASKS = 'USER_REDUCER/FETCH_TASKS';
export const FETCH_TASKS_SUCCESS = 'USER_REDUCER/FETCH_TASKS_SUCCESS';
export const FETCH_TASKS_FAILED = 'USER_REDUCER/FETCH_TASKS_FAILED';

export const FETCH_USERS = 'USER_REDUCER/FETCH_USERS';
export const FETCH_USERS_SUCCESS = 'USER_REDUCER/FETCH_USERS_SUCCESS';
export const FETCH_USERS_FAILED = 'USER_REDUCER/FETCH_USERS_FAILED';

export const FETCH_TASK_ADD = 'REDUCER/FETCH_TASK_ADD';
export const FETCH_TASK_UPDATE = 'REDUCER/FETCH_TASK_UPDATE';
export const FETCH_TASK_REMOVE = 'REDUCER/FETCH_TASK_REMOVE';

export const IS_LOADING = 'USER_REDUCER/IS_LOADING';

export const FETCH_SEARCHING_USERS = 'USER_REDUCER/FETCH_SEARCHING_USERS';
export const FETCH_SEARCHING_USERS_SUCCESS =
  'USER_REDUCER/FETCH_SEARCHING_USERS_SUCCESS ';

export const GET_CURRENT_USER = 'AUTH_REDUCER/GET_CURRENT_USER';
export const LOG_OUT_USER = 'AUTH_REDUCER/LOG_OUT_USER';
export const LOG_OUT_USER_SUCCESS = 'AUTH_REDUCER/LOG_OUT_USER_SUCCESS';
export const LOG_IN_USER = 'AUTH_REDUCER/LOG_IN_USER';

export const GET_CURRENT_USER_SUCCESS = 'AUTH_REDUCER/GET_CURRENT_USER_SUCCESS';

export const AUTH_FAILED = 'AUTH_REDUCER/AUTH_FAILED';
export const GET_CAME_USER ='AUTH_REDUCER/GET_CAME_USER';
export const GET_CAME_USER_SUCCESS ='AUTH_REDUCER/GET_CAME_USER_SUCCESS';

export const IS_SHOW_CHANGING_MESSAGE = 'REDUCER/IS_SHOW_CHANGING_MESSAGE';
